name: ziggle
description: ziggle
publish_to: 'none'
version: 4.0.1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  firebase_analytics: ^11.3.0
  firebase_messaging: ^15.1.0
  get_it: ^7.7.0
  injectable: ^2.4.4
  slang: ^3.31.2
  slang_flutter: ^3.31.0
  flutter_svg: ^2.0.10+1
  go_router: ^12.1.3
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  flutter_quill: ^10.5.13
  keyboard_actions: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  go_router_builder: ^2.7.1


flutter:
  uses-material-design: true
  assets:
    - assets/logo/fire.svg
    - assets/logo/short.svg
    - assets/logo/long.svg
    - assets/icons/
    - assets/images/
    - assets/fonts/TossFace/LICENSE
  fonts:
    - family: TossFace
      fonts:
        - asset: assets/fonts/TossFace/TossFaceFontWeb.otf

flutter_gen:
  integrations:
    flutter_svg: true
