name: ziggle
description: ziggle
publish_to: 'none'
version: 4.0.2

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  firebase_analytics: ^11.3.0
  firebase_messaging: ^15.1.0
  get_it: ^7.7.0
  injectable: ^2.4.4
  slang: ^3.31.2
  slang_flutter: ^3.31.0
  flutter_svg: ^2.0.10+1
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  flutter_quill: ^10.5.13
  keyboard_actions: ^4.2.0
  dotted_border: ^2.1.0
  intl: ^0.19.0
  sheet: ^1.0.0
  flutter_secure_storage: ^9.2.2
  dio: ^5.7.0
  flutter_web_auth_2: ^3.1.2
  cookie_jar: ^4.0.8
  path_provider: ^2.1.4
  dio_cookie_manager: ^3.1.1
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  rxdart: ^0.28.0
  flutter_bloc: ^8.1.6
  collection: ^1.18.0
  flutter_inappwebview: ^5.8.0
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  package_info_plus: ^8.0.2
  extended_text: ^14.1.0
  mutex: ^3.1.0
  auto_route: ^9.2.2
  flutter_local_notifications: ^17.2.2
  uni_links: ^0.5.1
  vsc_quill_delta_to_html: ^1.0.5
  dynamic_fonts: ^2.2.1
  flutter_quill_delta_from_html: ^1.4.1
  share_plus: ^10.0.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  retrofit_generator: ^9.1.2
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  auto_route_generator: ^9.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/logo/fire.svg
    - assets/logo/short.svg
    - assets/logo/long.svg
    - assets/icons/
    - assets/images/
    - assets/fonts/TossFace/LICENSE
  fonts:
    - family: TossFace
      fonts:
        - asset: assets/fonts/TossFace/TossFaceFontWeb.otf

flutter_gen:
  integrations:
    flutter_svg: true
